spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create-drop


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


cloud:
  aws:
    credentials:
      access-key: AKIA2WDABBCCTJOEEEDDVFFAZBZBZWJWNH
      secret-key: kxbS4eBQAAAG0+W01GqEWEW//CWZ00SyLADDJfJZvvJ4oWanW/
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: coldrain-f-bucket
